[package]
name = "voisss_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.3.1"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
exit_first = true
